# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/LoginD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 193)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 40, 291, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.username_field = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.username_field.setObjectName("username_field")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_field)
        self.password_field = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.password_field.setObjectName("password_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_field)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.signup_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.signup_btn.setObjectName("signup_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.signup_btn)
        self.login_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.login_btn.setObjectName("login_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.login_btn)
        self.label.setBuddy(self.username_field)
        self.label_2.setBuddy(self.password_field)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username_field, self.password_field)
        Dialog.setTabOrder(self.password_field, self.login_btn)
        Dialog.setTabOrder(self.login_btn, self.signup_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.signup_btn.setText(_translate("Dialog", "Sign Up"))
        self.login_btn.setText(_translate("Dialog", "Log In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
