# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 215)
        self.formLayout_2 = QtWidgets.QFormLayout(Dialog)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username_field = QtWidgets.QLineEdit(Dialog)
        self.username_field.setObjectName("username_field")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username_field)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password_field = QtWidgets.QLineEdit(Dialog)
        self.password_field.setObjectName("password_field")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_field)
        self.create_acc_btn = QtWidgets.QPushButton(Dialog)
        self.create_acc_btn.setObjectName("create_acc_btn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.create_acc_btn)
        self.existing_signin_btn = QtWidgets.QPushButton(Dialog)
        self.existing_signin_btn.setObjectName("existing_signin_btn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.existing_signin_btn)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.formLayout)
        self.label.setBuddy(self.username_field)
        self.label_2.setBuddy(self.password_field)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.create_acc_btn.setText(_translate("Dialog", "Create Account"))
        self.existing_signin_btn.setText(_translate("Dialog", "Sign In With Existing Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
